defaults: &defaults
  app_name: ShopQi App Example
  author:
    email: mahb45@gmail.com
  oauth:
    client_id: f04bfb5c3f6a0380e2a8f5c64a1aed6bdb1ac7554e0a77a3f1992e087bce3479
    secret: 7d561bb675cf3eba72830a99f0c70321d822643219b89a43b7b329ca9426a503
    scope: 'read_products read_orders'
    callback_path: '/callback'
  domain:
    host: 'example.shopqiapp.com' # 邮件发送配置
    record: 粤ICP备11089804号
  shopqi_domain:
    protocol: 'http://'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  oauth:
    client_id: f04bfb5c3f6a0380e2a8f5c64a1aed6bdb1ac7554e0a77a3f1992e087bce3479
    client_secret: 7d561bb675cf3eba72830a99f0c70321d822643219b89a43b7b329ca9426a503
    scope: 'read_products read_orders'
    callback_path: '/callback'
  domain:
    host: 'example.shopqiapp.com'
    record: 粤ICP备11089804号
  shopqi_domain:
    protocol: 'https://'
